---
# Check to see if CSF is already installed
# TODO: this depends that CSF is in the users path
- name: check if csf is installed
  command: csf -v
  register: result
  ignore_errors: true
  changed_when: false

# Download the CSF file
- name: download csf files
  get_url:
    dest: /usr/src/csf.tgz
    url: https://download.configserver.com/csf.tgz
  when: result|failed

# Extract tar.gz
- name: extract csf files
  unarchive:
    src: /usr/src/csf.tgz
    dest: /usr/src
    copy: no
  when: result|failed

# Install lib-perl which is sometimes required for retrieving HTTPS URL's
- name: install package libwww-perl [Debian]
  apt: name=libwww-perl state=present
  when: "ansible_os_family == 'Debian'"

- name: install package perl-libwww-perl [RedHat]
  yum: name=perl-libwww-perl state=present
  when: "ansible_os_family == 'RedHat'"

# Install ipset if desired
- name: install package ipset [Debian]
  apt: name=ipset state=present
  when: "ipset and ansible_os_family == 'Debian'"

- name: install package ipset [RedHat]
  yum: name=ipset state=present
  when: "ipset and ansible_os_family == 'RedHat'"

# Install perl GD Graph if desired
- name: install package libgd-graph-perl [Debian]
  apt: name=libgd-graph-perl state=present
  when: "statistical_graphs and ansible_os_family == 'Debian'"

- name: install package perl-GDGraph [RedHat]
  yum: name=perl-GDGraph state=present
  when: "statistical_graphs and ansible_os_family == 'RedHat'"

# Firewalld needs to be disabled to prevent bad stuff from happening with CSF in CentOS7
- name: Disable firewalld on [RedHat] and [CentOS7]
  service: name=firewalld state=stopped enabled=no
  register: disable_firewalld
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  failed_when: "disable_firewalld|failed and 'could not find' not in disable_firewalld.msg"

# ifconfig (net-tools) needs to be installed for CSF to work properly in CentOS7
- name: install package net-tools [RedHat]
  yum: name=net-tools state=present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

# Install CSF
- name: install csf
  command: sh install.sh
  args:
    chdir: /usr/src/csf
  when: result|failed

# Cleanup TEMP dir we created
- name: cleanup csf files
  file: path={{ item }} state=absent
  with_items:
   - /usr/src/csf
   - /usr/src/csf.tgz
